repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: python3 -m ruff check .
        language: system
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: python3 -m pytest
        language: system
        pass_filenames: false
      - id: interrogate
        name: interrogate
        entry: python3 -m interrogate -c pyproject.toml
        language: system
        pass_filenames: false
      - id: build
        name: build
        entry: python3 -m build
        language: system
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: python3 -m mypy src/ tests/
        language: system
        pass_filenames: false
      - id: test-and-shields
        name: test-and-shields
        entry: bash scripts/update_shields.sh
        language: system
        pass_filenames: false
